= ConOps

The ConOps, at the organization level, addresses the leadership's intended way of operating the organization. It may refer to the use of one or more systems, as black boxes, to forward the organization's goals and objectives. The ConOps document describes the organization's assumptions or intent in regard to an overall operation or series of operations of the business with using the system to be developed, existing systems, and possible future systems. This document is frequently embodied in long-range strategic plans and annual operational plans. The ConOps document serves as a basis for the organization to direct the overall characteristics of the future business and systems, for the project to understand its background, and for the users of this International Standard to implement the stakeholder requirements elicitation. The ConOps document should include the following information items. 

== Purpose

Describe the purpose of this document by describing the current status of the organization, the goal of the long-range strategic plan, and gaps between them.

== Scope

Describe the scope of this document by specifying the organization's business domains to which it applies.

== Strategic plan

Describe the long-range strategic plan for the organization's business and resultant systems. This includes description when the current business of the organization should be changed and what systems should be implemented and operated. The plan may contain options with priority.

== Effectiveness

Estimate the effectiveness expected by implementing the plan.

== Overall operation

=== Context

Describe an overall view for the organization's business, which business function or organizational unit is covered by which existing systems, and which is to be covered by planned systems. For more detailed description, major data resources and flows may be mapped onto the view.

=== Systems

List and outline the existing systems and systems to be developed in the future.

=== Organizational Unit

List and relate with each other the organizational units that play roles in business operation, systems operation, and their management.

:plantuml-server-url: http://www.plantuml.com/plantuml

[plantuml]
....
left to right direction
skinparam packageStyle rectangle
actor :Environmental Test Engineer:
actor :Flight Controller:
actor :Payload Operator:
actor :Solar Simulation Chamber:

rectangle (DellSat-77\nSatellite) {
left to right direction
:Environmental Test Engineer: -- (Generate\nelectricity\nfrom\nsolar panaels)
:Flight Controller: -- (Execute\nHohmann\ntransfer)
:Payload Operator: -- (Point infraraed\nsensor at target)
:Payload Operator: -- (Get payload\nhealth and status)

(Execute\nHohmann\ntransfer) .> (Send command): <<include>>
(Point infraraed\nsensor at target) .> (Send command): <<include>>
(Get payload\nhealth and status) .> (Send command): <<include>>
(Send command) <|- (Send stored\ncommand)
(Send command) <|- (Send real-time\ncommand) 
(Generate\nelectricity\nfrom\nsolar panaels) -- :Solar Simulation Chamber:
}
....
_Use case diagram illustrating Concept of Operations for DellSat-77 Satellite_.footnote:[Delligatti, L. (2014). SysML distilled. 2nd ed. Addison-Wesley Professional, p.82.]

== Governance

=== Governance policies

Describe policies or principles which will govern any critical business and technological decisions in implementing the plan.

=== Organization

Describe the organization unit that is responsible for the governance, and describe policies on organizational structure and human resource in system development.

=== Investment plan

Describe plans on possible investment for the development of systems and depict how the policies should be managed.

=== Information asset management

Describe policies of how information assets are managed and define which organizational unit is responsible for the management.

=== Security

Describe policies on security.

=== Business continuity plan

Describe policies on business continuity plan. 

=== Compliance

Describe policies on regal and regulatory compliance. 


'''
===== Attribution

This document is adapted from the ISO/IEC/IEEE 29148:2011 _International Standard - Systems and software engineering -- Life cycle processes --Requirements engineering_, available at https://standards.ieee.org/standard/29148-2011.html.

===== Copyright (C) 2018

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program.  If not, see http://www.gnu.org/licenses/.